### ISSUE TITLE
Add automatic injection of types into packages

### ISSUE THREAD

**Issue by fikovnik** [PRL-PRG/contractR#1]
On package load it should inject types into all loaded packages as well as all to be loaded packages.

**Comment by aviralg** [comment]
Solved in [Add package hooks to automatically insert contracts](https://github.com/PRL-PRG/contractR/commit/58f66ba26c425bfebb8f684ac7caade2b652a612) and further enhanced in [Merge, fix and export environment contract insertion function](https://github.com/PRL-PRG/contractR/commit/a15616d23b77ed7397a39dc62aa66acc3d034e3e).
